Feat/tooltip
VanessaMartinsG/Filmate pull request #8
Opened 2023-01-13 03:23 UTC by VanessaMartinsG

Adicionado caixa de erro para o usuário não logado e para falha ao logar.

2023-01-13 11:16 UTC, BrunoPittaF requested changes
Reprovado por causa do comentário, hoje faremos um code review ao vivo mostrando as alterações necessárias (muitas)

2023-01-13 11:16 UTC, BrunoPittaF commented on src/pages/login/login.ts
> +setTimeout(function () {
Por que tem um setTimeout aqui? Não deveria existir.

2023-01-13 11:16 UTC, BrunoPittaF commented on src/pages/login/login.ts
> +  Toastify({
O Toastify é um componente que vai se repetir a medida que o sistema é desenvolvido, a implementação não está errada, mas não comporta a sua utilidade.

2023-01-13 11:16 UTC, BrunoPittaF commented on src/scss/tooltip.scss
> +.toastify {
O Toastify é um componente que vai se repetir a medida que o sistema é desenvolvido, a implementação não está errada, mas não comporta a sua utilidade. O CSS deve ser global

2023-01-14 01:34 UTC, VanessaMartinsG commented
Feita as alterações solicitadas

2023-01-14 13:11 UTC, BrunoPittaF approved these changes
Aprovado, fiz algumas alterações eu mesmo como dito.

Pode mergear

2023-01-15 00:53 UTC, merged